# Generated by Django 4.2.5 on 2023-09-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_description_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgae',
            new_name='image',
        ),
    ]
