# Generated by Django 4.2.5 on 2023-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_productreviews_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='review',
            field=models.TextField(),
        ),
    ]
